#!/bin/csh
#
# Installs all .py files under the specified directory

setenv INSTDIR	$1

if ( ! -d $INSTDIR ) then
	echo "$INSTDIR not a directory!"
	exit 1
endif

foreach i (*.py)
cp $i $INSTDIR
chmod ug+w $INSTDIR/$i
end
